spring.application.name=backend

spring.datasource.url=jdbc:postgresql://gondola.proxy.rlwy.net:13243/railway
spring.datasource.username=postgres
spring.datasource.password=QsdyncrzVkkWreAVGsyQcBakYGGPGXRK
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true